# Generated by Django 4.2.2 on 2023-08-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='文')),
                ('map_url', models.TextField(blank=True, null=True, verbose_name='MAPソースコード')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン画像')),
                ('member', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(blank=True, max_length=100, null=True, verbose_name='id1')),
                ('id2', models.CharField(blank=True, max_length=100, null=True, verbose_name='id1')),
                ('id3', models.CharField(blank=True, max_length=100, null=True, verbose_name='id1')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_to_m', to='mymapapp.site', unique=True, verbose_name='saito')),
            ],
        ),
        migrations.CreateModel(
            name='LiketoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ManyToManyField(blank=True, null=True, related_name='s_to_like', to='mymapapp.site', verbose_name='saito')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_to_like', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_number', models.IntegerField(blank=True, null=True, verbose_name='ジャンル番号')),
                ('ver', models.IntegerField(blank=True, default=0, null=True, verbose_name='バージョン番号')),
                ('title', models.CharField(blank=True, max_length=34, null=True, verbose_name='タイトル')),
                ('text1', models.TextField(blank=True, null=True, verbose_name='文1')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='文2')),
                ('text3', models.TextField(blank=True, null=True, verbose_name='文3')),
                ('text4', models.TextField(blank=True, null=True, verbose_name='文4')),
                ('pre_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='前に置かれるコンテンツ番号')),
                ('next_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='後ろに置かれるコンテンツ番号')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_to_c', to='mymapapp.site', verbose_name='saito')),
            ],
        ),
    ]
